plugins {
    id 'com.android.application'
}

android {
    namespace 'com.isthmus.mesh'
    compileSdk 34

    defaultConfig {
        applicationId "com.isthmus.mesh"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "0.5.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Zero bloated third-party dependencies: Pure native Android SDK & WebKit
}
